"""
Verdict Engine
Combines fact-checker verdicts and news corroboration into a composite verdict.
AI content detection is shown as info-only — it does NOT influence the verdict score.

Now supports two modes:
1. Gemini AI synthesis (preferred) — sends all evidence to Gemini for an AI verdict
2. Rule-based fallback — uses weighted scoring when Gemini is unavailable
"""

from app.services.gemini_service import synthesize_verdict_with_gemini

# ─── Verdict Labels ────────────────────────────────────────────────
VERDICT_LEVELS = [
    {"min": 0.75, "label": "VERIFIED",     "color": "green",  "icon": "check"},
    {"min": 0.60, "label": "LIKELY TRUE",  "color": "lime",   "icon": "check"},
    {"min": 0.40, "label": "UNVERIFIED",   "color": "yellow", "icon": "alert"},
    {"min": 0.25, "label": "LIKELY FALSE", "color": "orange", "icon": "alert"},
    {"min": -2.0, "label": "FALSE",        "color": "red",    "icon": "x"},
]

VERDICT_COLORS = {
    "VERIFIED": "green",
    "LIKELY TRUE": "lime",
    "UNVERIFIED": "yellow",
    "LIKELY FALSE": "orange",
    "FALSE": "red",
}


def _get_verdict_label(score: float) -> dict:
    """Map a score to a verdict label."""
    for level in VERDICT_LEVELS:
        if score >= level["min"]:
            return level
    return VERDICT_LEVELS[-1]


def _compute_fallback_verdict(
    factcheck_result: dict,
    corroboration_result: dict,
    ai_detection: dict | None = None,
    wikipedia_result: dict | None = None,
) -> dict:
    """
    Legacy rule-based verdict computation.
    Used as fallback when Gemini is unavailable.

    Weights when fact-checkers have results:
    - Fact-checker verdicts: 80%
    - News corroboration:    20%

    Weights when NO fact-checker results:
    - News corroboration:    100%
    """

    # ── 1. Fact-checker score (most reliable signal) ──
    fc_has_results = factcheck_result.get("has_results", False)
    fc_score = factcheck_result.get("verdict_score", 0.0)

    # Normalize fact-checker score from [-1, 1] to [0, 1]
    fc_normalized = (fc_score + 1) / 2  # -1→0, 0→0.5, 1→1.0

    # ── 2. Corroboration score (already 0-1) ──
    corr_score = corroboration_result.get("score", 0.5)

    # ── 3. AI detection (info-only, no weight on verdict) ──
    ai_label = "Unknown"
    if ai_detection:
        prediction = ai_detection.get("prediction", "").lower()
        if prediction == "real":
            ai_label = "Human-written"
        elif prediction == "fake":
            ai_label = "AI-generated"

    # ── Compute weighted composite (AI excluded) ──
    if fc_has_results:
        # Fact-checkers explicitly rated this — they are the authority
        corr_effective = corr_score if corroboration_result.get("total_count", 0) > 0 else fc_normalized
        composite = (fc_normalized * 0.80) + (corr_effective * 0.20)
    else:
        # No fact-checker data — rely entirely on corroboration
        composite = corr_score

    # Clamp to [0, 1]
    composite = max(0.0, min(1.0, composite))

    # Get verdict label
    verdict_info = _get_verdict_label(composite)

    # Build a fallback explanation
    explanation_parts = []
    if fc_has_results:
        claims = factcheck_result.get("claims", [])
        ratings = [c.get("rating", "N/A") for c in claims[:3]]
        explanation_parts.append(
            f"Professional fact-checkers rated this claim as: {', '.join(ratings)}."
        )
    else:
        explanation_parts.append(
            "No professional fact-checker verdicts were found for this claim."
        )

    credible_count = corroboration_result.get("credible_count", 0)
    total_count = corroboration_result.get("total_count", 0)
    if total_count > 0:
        explanation_parts.append(
            f"News corroboration found {credible_count} credible source(s) out of {total_count} results."
        )
    else:
        explanation_parts.append("No corroborating news sources were found.")

    if wikipedia_result and wikipedia_result.get("has_results"):
        wiki_titles = [a["title"] for a in wikipedia_result.get("articles", [])[:2]]
        explanation_parts.append(
            f"Related Wikipedia articles found: {', '.join(wiki_titles)}."
        )

    explanation_parts.append(
        "(This analysis was generated by the rule-based fallback engine. "
        "Enable the Gemini API for AI-powered analysis.)"
    )

    # Build fallback evidence analysis
    evidence_analysis = [
        {
            "source": "Fact-Checkers",
            "finding": f"Found {len(factcheck_result.get('claims', []))} matching fact-check(s)" if fc_has_results else "No matching fact-checks found",
            "impact": "positive" if fc_has_results and fc_score > 0 else "negative" if fc_has_results and fc_score < 0 else "unavailable",
        },
        {
            "source": "News Corroboration",
            "finding": f"{credible_count} credible source(s) found out of {total_count}" if total_count > 0 else "No corroborating news articles found",
            "impact": "positive" if credible_count >= 2 else "neutral" if credible_count == 1 else "unavailable",
        },
        {
            "source": "Wikipedia",
            "finding": f"Found {len(wikipedia_result.get('articles', []))} related article(s)" if wikipedia_result and wikipedia_result.get("has_results") else "No relevant Wikipedia articles found",
            "impact": "neutral" if wikipedia_result and wikipedia_result.get("has_results") else "unavailable",
        },
        {
            "source": "AI Detection",
            "finding": f"Text appears to be {ai_label.lower()}" if ai_label != "Unknown" else "AI detection not available",
            "impact": "neutral",
        },
    ]

    return {
        "verdict": verdict_info["label"],
        "verdict_score": round(composite, 3),
        "verdict_color": verdict_info["color"],
        "explanation": " ".join(explanation_parts),
        "evidence_analysis": evidence_analysis,
        "engine": "fallback",

        # Evidence breakdown (kept for backwards compatibility)
        "evidence": {
            "factcheck": {
                "score": round(fc_normalized, 2),
                "raw_score": fc_score,
                "has_results": fc_has_results,
                "claims": factcheck_result.get("claims", []),
                "weight": "80%" if fc_has_results else "—",
            },
            "corroboration": {
                "score": corr_score,
                "credible_count": credible_count,
                "total_count": total_count,
                "top_sources": corroboration_result.get("top_sources", []),
                "weight": "20%" if fc_has_results else "100%",
            },
            "ai_detection": {
                "label": ai_label,
                "raw_prediction": ai_detection.get("prediction", "N/A") if ai_detection else "N/A",
                "raw_confidence": ai_detection.get("confidence", 0) if ai_detection else 0,
                "weight": "Info only",
            },
            "wikipedia": {
                "has_results": wikipedia_result.get("has_results", False) if wikipedia_result else False,
                "articles": wikipedia_result.get("articles", []) if wikipedia_result else [],
                "search_terms": wikipedia_result.get("search_terms", "") if wikipedia_result else "",
            },
        },
    }


async def compute_verdict(
    claim_text: str,
    factcheck_result: dict,
    corroboration_result: dict,
    ai_detection: dict | None = None,
    wikipedia_result: dict | None = None,
    source_info: dict | None = None,
) -> dict:
    """
    Compute the final verdict using Gemini AI (preferred) or fallback rules.

    1. Try Gemini: send all evidence for AI-synthesized verdict
    2. If Gemini fails: fall back to rule-based composite scoring
    """

    # ── Try Gemini AI synthesis first ──
    gemini_result = await synthesize_verdict_with_gemini(
        claim_text=claim_text,
        factcheck_result=factcheck_result,
        corroboration_result=corroboration_result,
        wikipedia_result=wikipedia_result or {"has_results": False, "articles": []},
        ai_detection=ai_detection,
        source_info=source_info,
    )

    if gemini_result:
        # ── Gemini succeeded — build response from AI verdict ──
        verdict = gemini_result["verdict"]
        score = gemini_result["confidence_score"]

        # ── AI detection (info-only) ──
        ai_label = "Unknown"
        if ai_detection:
            prediction = ai_detection.get("prediction", "").lower()
            if prediction == "real":
                ai_label = "Human-written"
            elif prediction == "fake":
                ai_label = "AI-generated"

        # ── Fact-checker normalized score ──
        fc_has_results = factcheck_result.get("has_results", False)
        fc_score = factcheck_result.get("verdict_score", 0.0)
        fc_normalized = (fc_score + 1) / 2

        corr_score = corroboration_result.get("score", 0.5)
        credible_count = corroboration_result.get("credible_count", 0)
        total_count = corroboration_result.get("total_count", 0)

        return {
            "verdict": verdict,
            "verdict_score": score,
            "verdict_color": VERDICT_COLORS.get(verdict, "yellow"),
            "explanation": gemini_result.get("explanation", ""),
            "evidence_analysis": gemini_result.get("evidence_analysis", []),
            "engine": "gemini",

            # Evidence breakdown (kept for backwards compatibility)
            "evidence": {
                "factcheck": {
                    "score": round(fc_normalized, 2),
                    "raw_score": fc_score,
                    "has_results": fc_has_results,
                    "claims": factcheck_result.get("claims", []),
                    "weight": "80%" if fc_has_results else "—",
                },
                "corroboration": {
                    "score": corr_score,
                    "credible_count": credible_count,
                    "total_count": total_count,
                    "top_sources": corroboration_result.get("top_sources", []),
                    "weight": "20%" if fc_has_results else "100%",
                },
                "ai_detection": {
                    "label": ai_label,
                    "raw_prediction": ai_detection.get("prediction", "N/A") if ai_detection else "N/A",
                    "raw_confidence": ai_detection.get("confidence", 0) if ai_detection else 0,
                    "weight": "Info only",
                },
                "wikipedia": {
                    "has_results": wikipedia_result.get("has_results", False) if wikipedia_result else False,
                    "articles": wikipedia_result.get("articles", []) if wikipedia_result else [],
                    "search_terms": wikipedia_result.get("search_terms", "") if wikipedia_result else "",
                },
            },
        }

    # ── Gemini unavailable — fall back to rules engine ──
    print("[INFO] Using fallback rule-based verdict engine.")
    return _compute_fallback_verdict(
        factcheck_result=factcheck_result,
        corroboration_result=corroboration_result,
        ai_detection=ai_detection,
        wikipedia_result=wikipedia_result,
    )
